version: "3"

services:

  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - /opt/mattermost/volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data:z
      - /etc/localtime:/etc/localtime:ro,z
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmdb_replaceme
      - POSTGRES_DB=mattermost

  app:
    build:
      context: app
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - /opt/mattermost/volumes/app/mattermost/config:/mattermost/config:rw,z
      - /opt/mattermost/volumes/app/mattermost/data:/mattermost/data:rw,z
      - /opt/mattermost/volumes/app/mattermost/logs:/mattermost/logs:rw,z
      - /opt/mattermost/volumes/app/mattermost/plugins:/mattermost/plugins:rw,z
      - /opt/mattermost/volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw,z
      - /etc/localtime:/etc/localtime:ro,z
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmdb_replaceme
      - MM_DBNAME=mattermost
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmdb_replaceme@db:5432/mattermost?sslmode=disable&connect_timeout=10
